liquetsoft_fias:
    # сущность, которая хранит версии ФИАС
    version_manager_entity: App\Entity\FiasVersion
    # массив, в котором указывается какие сущности в какой объект преобразовывать
    entity_bindings:
        ActualStatus: App\Entity\ActualStatus
        AddressObject: App\Entity\AddressObject
        AddressObjectType: App\Entity\AddressObjectType
        CenterStatus: App\Entity\CenterStatus
        CurrentStatus: App\Entity\CurrentStatus
        EstateStatus: App\Entity\EstateStatus
        FlatType: App\Entity\FlatType
        House: App\Entity\House
        HouseStateStatus: App\Entity\HouseStateStatus
        IntervalStatus: App\Entity\IntervalStatus
        NormativeDocument: App\Entity\NormativeDocument
        NormativeDocumentType: App\Entity\NormativeDocumentType
        OperationStatus: App\Entity\OperationStatus
        Room: App\Entity\Room
        RoomType: App\Entity\RoomType
        Stead: App\Entity\Stead
        StructureStatus: App\Entity\StructureStatus
