version: '3.7'

services:

    postgres:
        container_name: fias-db
        build:
            context: local/postgres
        ports:
            - 5432:5432
        volumes:
            - fias_database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DOCKER_DB_USER}
            POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
            POSTGRES_DB: ${DOCKER_DB_NAME}
            PGDATA: /var/lib/postgresql/data/pgdata

    php:
        container_name: fias-php
        build:
            context: local/php
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        volumes:
            - ${DOCKER_APP_PATH}:/var/www:cached

    nginx:
        container_name: fias-nginx
        build:
            context: local/nginx
            args:
                HOST_USER_ID: ${DOCKER_USER_ID}
                HOST_GROUP_ID: ${DOCKER_GROUP_ID}
        ports:
            - 8080:80
        volumes:
            - ${DOCKER_APP_PATH}:/var/www:cached

volumes:
    fias_database:
