App\Entity\ActualStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\AddressObject:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\AddressObjectType:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\CenterStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\CurrentStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\EstateStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\FlatType:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\House:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\HouseStateStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\IntervalStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\NormativeDocument:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\NormativeDocumentType:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\OperationStatus:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\Room:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\RoomType:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\Stead:
    collectionOperations:
        - get
    itemOperations:
        - get



App\Entity\StructureStatus:
    collectionOperations:
        - get
    itemOperations:
        - get
